### PR TITLE
Fix the field name from https://api.gfycat.com/v1/gfycats

### PR DESCRIPTION
**Pull request by hanxue**
Should be `gfyname`, not `name`

### CODE REVIEW

**Comment by markasoftware** [comment]
`gif-is-jif` is no longer maintained; it's been replaced by my project [Anypaste](https://anypaste.xyz), which still supports Gfycat uploading (if you run `anypaste -p gfycat /path/filename`), but supports many other sites too! If you are in a mood for contributing to projects, it could use some more plugins to support more sites. The repo is [here](https://github.com/markasoftware/anypaste).

I'll accept this pull request anyways.

**Comment by hanxue** [comment]
I love anypaste! Glad that you publish that project. I just created a Homebrew Tap at https://github.com/hanxue/homebrew-cmd to make useful scripts available via homebrew. 

Could you consider creating a release for anypaste, so that it can be installed using Homebrew without the `--HEAD` flag?

**Comment by markasoftware** [comment]
I've tagged the current commit as v1.0.0. Thanks for creating a Homebrew tap, I'm not much of a Mac guy so people like you can hopefully make it more usable there!

**Comment by hanxue** [comment]
Thanks great! I have updated the formula with version 1.0.1 😄

**Pull request merged**
